services:
  - type: web
    name: arr-wallet
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REDIS_URL
        sync: false
      - key: NEXT_PUBLIC_API_URL
        value: /api
      - key: NEXT_PUBLIC_SOCKET_URL
        value: ""
